// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  coverUrl: __t.option(__t.string()).name("cover_url"),
  purchaseLink: __t.option(__t.string()).name("purchase_link"),
  played: __t.option(__t.bool()),
  subtitle: __t.option(__t.string()),
  genre: __t.option(__t.string()),
});
