// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.identity().primaryKey(),
  name: __t.string(),
  bio: __t.string(),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  socialLinks: __t.string().name("social_links"),
  streamStatus: __t.string().name("stream_status"),
});
