// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  messageType: __t.string().name("message_type"),
  channelId: __t.u64().name("channel_id"),
  sender: __t.identity(),
  userIdentity: __t.identity().name("user_identity"),
  createdAt: __t.timestamp().name("created_at"),
  content: __t.option(__t.string()),
});
