// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const Credentials = __t.object("Credentials", {
  identity: __t.identity(),
  username: __t.string(),
  passwordHash: __t.string(),
});
export type Credentials = __Infer<typeof Credentials>;

export const LinkPreview = __t.object("LinkPreview", {
  url: __t.string(),
  title: __t.string(),
  description: __t.string(),
  image: __t.string(),
  fetchedAt: __t.timestamp(),
});
export type LinkPreview = __Infer<typeof LinkPreview>;

export const LinkPreviewResult = __t.object("LinkPreviewResult", {
  url: __t.string(),
  title: __t.string(),
  description: __t.string(),
  image: __t.string(),
});
export type LinkPreviewResult = __Infer<typeof LinkPreviewResult>;

export const Message = __t.object("Message", {
  sender: __t.identity(),
  sent: __t.timestamp(),
  text: __t.string(),
  channelId: __t.u64(),
});
export type Message = __Infer<typeof Message>;

export const MessageLike = __t.object("MessageLike", {
  messageSent: __t.timestamp(),
  userIdentity: __t.identity(),
});
export type MessageLike = __Infer<typeof MessageLike>;

export const MessageReaction = __t.object("MessageReaction", {
  messageSent: __t.timestamp(),
  userIdentity: __t.identity(),
  emoji: __t.string(),
});
export type MessageReaction = __Infer<typeof MessageReaction>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

