// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminReportedMessages = __t.object("AdminReportedMessages", {});
export type AdminReportedMessages = __Infer<typeof AdminReportedMessages>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  isLiveChat: __t.bool(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelUnread = __t.object("ChannelUnread", {
  userIdentity: __t.identity(),
  channelId: __t.u64(),
  lastReadAt: __t.timestamp(),
});
export type ChannelUnread = __Infer<typeof ChannelUnread>;

export const Credentials = __t.object("Credentials", {
  identity: __t.identity(),
  username: __t.string(),
  passwordHash: __t.string(),
});
export type Credentials = __Infer<typeof Credentials>;

export const LinkPreview = __t.object("LinkPreview", {
  url: __t.string(),
  title: __t.string(),
  description: __t.string(),
  image: __t.string(),
  fetchedAt: __t.timestamp(),
});
export type LinkPreview = __Infer<typeof LinkPreview>;

export const LinkPreviewResult = __t.object("LinkPreviewResult", {
  url: __t.string(),
  title: __t.string(),
  description: __t.string(),
  image: __t.string(),
});
export type LinkPreviewResult = __Infer<typeof LinkPreviewResult>;

export const Message = __t.object("Message", {
  sender: __t.identity(),
  sent: __t.timestamp(),
  text: __t.string(),
  channelId: __t.u64(),
});
export type Message = __Infer<typeof Message>;

export const MessageLike = __t.object("MessageLike", {
  messageSent: __t.timestamp(),
  userIdentity: __t.identity(),
});
export type MessageLike = __Infer<typeof MessageLike>;

export const MessageReaction = __t.object("MessageReaction", {
  messageSent: __t.timestamp(),
  userIdentity: __t.identity(),
  emoji: __t.string(),
});
export type MessageReaction = __Infer<typeof MessageReaction>;

export const MySessionMetrics = __t.object("MySessionMetrics", {});
export type MySessionMetrics = __Infer<typeof MySessionMetrics>;

export const ReportedMessage = __t.object("ReportedMessage", {
  id: __t.u64(),
  messageSent: __t.timestamp(),
  reporterIdentity: __t.identity(),
  reportedAt: __t.timestamp(),
  status: __t.string(),
});
export type ReportedMessage = __Infer<typeof ReportedMessage>;

export const ReportedMessageView = __t.object("ReportedMessageView", {
  id: __t.u64(),
  messageSent: __t.timestamp(),
  reporterIdentity: __t.identity(),
  reportedAt: __t.timestamp(),
  status: __t.string(),
});
export type ReportedMessageView = __Infer<typeof ReportedMessageView>;

export const SessionMetrics = __t.object("SessionMetrics", {
  sessionCount: __t.u64(),
  connectedAt: __t.option(__t.timestamp()),
});
export type SessionMetrics = __Infer<typeof SessionMetrics>;

export const StreamScheduleDay = __t.object("StreamScheduleDay", {
  dayNumber: __t.u32(),
  theme: __t.string(),
  description: __t.option(__t.string()),
});
export type StreamScheduleDay = __Infer<typeof StreamScheduleDay>;

export const StreamerProfile = __t.object("StreamerProfile", {
  id: __t.identity(),
  name: __t.string(),
  bio: __t.string(),
  avatarUrl: __t.option(__t.string()),
  socialLinks: __t.string(),
  streamStatus: __t.string(),
});
export type StreamerProfile = __Infer<typeof StreamerProfile>;

export const SystemMessage = __t.object("SystemMessage", {
  id: __t.u64(),
  messageType: __t.string(),
  channelId: __t.u64(),
  sender: __t.identity(),
  userIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  content: __t.option(__t.string()),
});
export type SystemMessage = __Infer<typeof SystemMessage>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  avatarUrl: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

export const UserSession = __t.object("UserSession", {
  sessionId: __t.u64(),
  userIdentity: __t.identity(),
  clientId: __t.option(__t.string()),
  connectedAt: __t.timestamp(),
  disconnectedAt: __t.option(__t.timestamp()),
});
export type UserSession = __Infer<typeof UserSession>;

