// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as FetchLinkPreviewProcedure from "../fetch_link_preview_procedure";

export type FetchLinkPreviewArgs = __Infer<typeof FetchLinkPreviewProcedure.params>;
export type FetchLinkPreviewResult = __Infer<typeof FetchLinkPreviewProcedure.returnType>;

