// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as EnrichFromIgdbProcedure from "../enrich_from_igdb_procedure";
import * as EnrichLibraryCoversProcedure from "../enrich_library_covers_procedure";
import * as FetchLinkPreviewProcedure from "../fetch_link_preview_procedure";
import * as SyncGamesFromSheetProcedure from "../sync_games_from_sheet_procedure";
import * as SyncLibraryFromSheetProcedure from "../sync_library_from_sheet_procedure";
import * as ValidateLibraryDataProcedure from "../validate_library_data_procedure";

export type EnrichFromIgdbArgs = __Infer<typeof EnrichFromIgdbProcedure.params>;
export type EnrichFromIgdbResult = __Infer<typeof EnrichFromIgdbProcedure.returnType>;
export type EnrichLibraryCoversArgs = __Infer<typeof EnrichLibraryCoversProcedure.params>;
export type EnrichLibraryCoversResult = __Infer<typeof EnrichLibraryCoversProcedure.returnType>;
export type FetchLinkPreviewArgs = __Infer<typeof FetchLinkPreviewProcedure.params>;
export type FetchLinkPreviewResult = __Infer<typeof FetchLinkPreviewProcedure.returnType>;
export type SyncGamesFromSheetArgs = __Infer<typeof SyncGamesFromSheetProcedure.params>;
export type SyncGamesFromSheetResult = __Infer<typeof SyncGamesFromSheetProcedure.returnType>;
export type SyncLibraryFromSheetArgs = __Infer<typeof SyncLibraryFromSheetProcedure.params>;
export type SyncLibraryFromSheetResult = __Infer<typeof SyncLibraryFromSheetProcedure.returnType>;
export type ValidateLibraryDataArgs = __Infer<typeof ValidateLibraryDataProcedure.params>;
export type ValidateLibraryDataResult = __Infer<typeof ValidateLibraryDataProcedure.returnType>;

