// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateChannelReducer from "../create_channel_reducer";
import DeleteChannelReducer from "../delete_channel_reducer";
import LoginReducer from "../login_reducer";
import RegisterReducer from "../register_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetNameReducer from "../set_name_reducer";
import ToggleLikeReducer from "../toggle_like_reducer";
import ToggleReactionReducer from "../toggle_reaction_reducer";
import UpdateChannelReducer from "../update_channel_reducer";

export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type DeleteChannelParams = __Infer<typeof DeleteChannelReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type ToggleLikeParams = __Infer<typeof ToggleLikeReducer>;
export type ToggleReactionParams = __Infer<typeof ToggleReactionReducer>;
export type UpdateChannelParams = __Infer<typeof UpdateChannelReducer>;

