// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CastVoteReducer from "../cast_vote_reducer";
import CleanupOldUserSessionsReducer from "../cleanup_old_user_sessions_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import DeleteChannelReducer from "../delete_channel_reducer";
import ImportLibraryBatchReducer from "../import_library_batch_reducer";
import ImportRecommendationsBatchReducer from "../import_recommendations_batch_reducer";
import InsertSystemMessageReducer from "../insert_system_message_reducer";
import LoginReducer from "../login_reducer";
import MarkChannelReadReducer from "../mark_channel_read_reducer";
import MarkGamePlayedReducer from "../mark_game_played_reducer";
import PopulateScheduleReducer from "../populate_schedule_reducer";
import RegisterReducer from "../register_reducer";
import ReportMessageReducer from "../report_message_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetNameReducer from "../set_name_reducer";
import SetSecretReducer from "../set_secret_reducer";
import ToggleLikeReducer from "../toggle_like_reducer";
import ToggleReactionReducer from "../toggle_reaction_reducer";
import UpdateStreamerProfileReducer from "../update_streamer_profile_reducer";

export type CastVoteParams = __Infer<typeof CastVoteReducer>;
export type CleanupOldUserSessionsParams = __Infer<typeof CleanupOldUserSessionsReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type DeleteChannelParams = __Infer<typeof DeleteChannelReducer>;
export type ImportLibraryBatchParams = __Infer<typeof ImportLibraryBatchReducer>;
export type ImportRecommendationsBatchParams = __Infer<typeof ImportRecommendationsBatchReducer>;
export type InsertSystemMessageParams = __Infer<typeof InsertSystemMessageReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type MarkChannelReadParams = __Infer<typeof MarkChannelReadReducer>;
export type MarkGamePlayedParams = __Infer<typeof MarkGamePlayedReducer>;
export type PopulateScheduleParams = __Infer<typeof PopulateScheduleReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type ReportMessageParams = __Infer<typeof ReportMessageReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetSecretParams = __Infer<typeof SetSecretReducer>;
export type ToggleLikeParams = __Infer<typeof ToggleLikeReducer>;
export type ToggleReactionParams = __Infer<typeof ToggleReactionReducer>;
export type UpdateStreamerProfileParams = __Infer<typeof UpdateStreamerProfileReducer>;

